<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/symfony/polyfill-php80/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php82/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-iconv/bootstrap.php';
require_once __DIR__ . '/php-di/php-di/src/functions.php';
